// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReKreator.DAL.EF;
using ReKreator.Domain.Enums;

namespace ReKreator.DAL.Migrations
{
    [DbContext(typeof(EventContext))]
    [Migration("20190326100551_AddingIdentityMigration")]
    partial class AddingIdentityMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ReKreator.Domain.Event", b =>
                {
                    b.Property<long>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(512);

                    b.Property<long>("Genre")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L);

                    b.Property<bool>("IsRemoved");

                    b.Property<string>("PosterUrl")
                        .HasMaxLength(1024);

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasMaxLength(254);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(128);

                    b.Property<byte>("Type")
                        .HasColumnType("tinyint");

                    b.HasKey("EventId");

                    b.HasIndex("Genre");

                    b.HasIndex("Type");

                    b.ToTable("Event");
                });

            modelBuilder.Entity("ReKreator.Domain.EventHolding", b =>
                {
                    b.Property<long>("EventHoldingId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("EventId")
                        .IsRequired();

                    b.Property<long?>("EventPlaceId")
                        .IsRequired();

                    b.Property<DateTime>("Time");

                    b.HasKey("EventHoldingId");

                    b.HasIndex("EventId");

                    b.HasIndex("EventPlaceId");

                    b.HasIndex("Time");

                    b.ToTable("EventHolding");
                });

            modelBuilder.Entity("ReKreator.Domain.EventHolding_User", b =>
                {
                    b.Property<long>("UserId");

                    b.Property<long>("EventHoldingId");

                    b.Property<DateTime?>("NotificationTimeBeforeEvent");

                    b.HasKey("UserId", "EventHoldingId");

                    b.HasIndex("EventHoldingId");

                    b.ToTable("EventHolding_User");
                });

            modelBuilder.Entity("ReKreator.Domain.EventPlace", b =>
                {
                    b.Property<long>("EventPlaceId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(128);

                    b.HasKey("EventPlaceId");

                    b.HasIndex("Title")
                        .IsUnique();

                    b.ToTable("EventPlace");
                });

            modelBuilder.Entity("ReKreator.Domain.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("UserId")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(128);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<string>("FirstName")
                        .HasMaxLength(64);

                    b.Property<string>("LastName")
                        .HasMaxLength(64);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(128);

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(64);

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("PasswordHash");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("User");
                });

            modelBuilder.Entity("ReKreator.Domain.User_UserRole", b =>
                {
                    b.Property<long>("UserId");

                    b.Property<long>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("User_UserRole");
                });

            modelBuilder.Entity("ReKreator.Domain.UserMailing", b =>
                {
                    b.Property<long>("UserMailingId");

                    b.Property<DateTime>("LasTimeMailed")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));

                    b.Property<byte>("MailingPeriod")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)0);

                    b.HasKey("UserMailingId");

                    b.ToTable("UserMailing");
                });

            modelBuilder.Entity("ReKreator.Domain.UserRole", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("UserRoleId")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32);

                    b.HasKey("Id");

                    b.ToTable("UserRole");
                });

            modelBuilder.Entity("ReKreator.Domain.EventHolding", b =>
                {
                    b.HasOne("ReKreator.Domain.Event", "Event")
                        .WithMany("EventsHoldings")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ReKreator.Domain.EventPlace", "EventPlace")
                        .WithMany("EventsHoldings")
                        .HasForeignKey("EventPlaceId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ReKreator.Domain.EventHolding_User", b =>
                {
                    b.HasOne("ReKreator.Domain.EventHolding", "EventHolding")
                        .WithMany("EventHoldings_Users")
                        .HasForeignKey("EventHoldingId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ReKreator.Domain.User", "User")
                        .WithMany("EventHoldings_Users")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ReKreator.Domain.User_UserRole", b =>
                {
                    b.HasOne("ReKreator.Domain.UserRole", "Role")
                        .WithMany("Users_UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ReKreator.Domain.User", "User")
                        .WithMany("Users_UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ReKreator.Domain.UserMailing", b =>
                {
                    b.HasOne("ReKreator.Domain.User")
                        .WithOne("UserMailing")
                        .HasForeignKey("ReKreator.Domain.UserMailing", "UserMailingId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
